export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const CLEAR_CART = 'CLEAR_CART';

export const SET_USER_INFO = 'SET_USER_INFO';

export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const ADD_SHIPPING_DETAILS = 'ADD_SHIPPING_DETAILS';
export const ADD_PAYMENT_METHOD = 'ADD_PAYMENT_METHOD';
